version: '3.4'

services:
  alarmservice.api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"