apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarmservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alarmservice
  template:
    metadata:
      labels:
        app: alarmservice
    spec:
      containers:
        - name: alarmservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"