apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: {{ .Values.redis.image }}
      ports:
        - containerPort: {{ .Values.redis.port }}