apiVersion: v1
kind: Service
metadata:
  name: alarmservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: alarmservice
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}